aliases: []
creation_timestamp: 1741107266065
current_stage: None
description: null
last_updated_timestamp: 1741107266065
name: SpamClassifier_random_forest_model
run_id: 2162d620250d44048e079a8e3e872101
run_link: null
source: file:///C:/Users/Bhuvnesh's PC/PycharmProjects/pythonProject/AML/Assignment
  2/runs/211292194086779681/2162d620250d44048e079a8e3e872101/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Bhuvnesh's PC/PycharmProjects/pythonProject/AML/Assignment
  2/runs/211292194086779681/2162d620250d44048e079a8e3e872101/artifacts/model
user_id: null
version: 1
