aliases: []
creation_timestamp: 1741107288281
current_stage: None
description: null
last_updated_timestamp: 1741107288281
name: SpamClassifier_svm_model
run_id: cf7700bf224649369e7ab5522524b189
run_link: null
source: file:///C:/Users/Bhuvnesh's PC/PycharmProjects/pythonProject/AML/Assignment
  2/runs/211292194086779681/cf7700bf224649369e7ab5522524b189/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Bhuvnesh's PC/PycharmProjects/pythonProject/AML/Assignment
  2/runs/211292194086779681/cf7700bf224649369e7ab5522524b189/artifacts/model
user_id: null
version: 1
