artifact_location: file:///C:/Users/Bhuvnesh's PC/PycharmProjects/pythonProject/AML/Assignment
  2/runs/211292194086779681
creation_time: 1741106994571
experiment_id: '211292194086779681'
last_update_time: 1741106994571
lifecycle_stage: active
name: Spam Classifier Experiment
