aliases: []
creation_timestamp: 1741107291399
current_stage: None
description: null
last_updated_timestamp: 1741107291399
name: SpamClassifier_naive_bayes_model
run_id: e8e86a2788844dee9725091fe8662d85
run_link: null
source: file:///C:/Users/Bhuvnesh's PC/PycharmProjects/pythonProject/AML/Assignment
  2/runs/211292194086779681/e8e86a2788844dee9725091fe8662d85/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Bhuvnesh's PC/PycharmProjects/pythonProject/AML/Assignment
  2/runs/211292194086779681/e8e86a2788844dee9725091fe8662d85/artifacts/model
user_id: null
version: 1
