aliases: []
creation_timestamp: 1741107233251
current_stage: None
description: null
last_updated_timestamp: 1741107233251
name: SpamClassifier_log_reg_model
run_id: 5a988d9440934ceead0c54d1dd4334f6
run_link: null
source: file:///C:/Users/Bhuvnesh's PC/PycharmProjects/pythonProject/AML/Assignment
  2/runs/211292194086779681/5a988d9440934ceead0c54d1dd4334f6/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Bhuvnesh's PC/PycharmProjects/pythonProject/AML/Assignment
  2/runs/211292194086779681/5a988d9440934ceead0c54d1dd4334f6/artifacts/model
user_id: null
version: 1
