artifact_location: file:///C:/Users/Bhuvnesh's PC/PycharmProjects/pythonProject/AML/Assignment
  2/runs/0
creation_time: 1741106994558
experiment_id: '0'
last_update_time: 1741106994558
lifecycle_stage: active
name: Default
